version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ~/postgres/typeorm:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - ${POSTGRES_PORT}:5432
  adminer:
    image: adminer
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: nette
    ports:
      - 9090:8080